package com.unibe.titulation.security.enums;

public enum RolName {
    ROLE_ADMIN, ROLE_USER, ROLE_STUDENT, ROLE_SECRETARY, ROLE_CAREER_DIRECTOR, ROLE_LIABLE_TT,
    ROLE_READER, ROLE_DEAN, ROLE_ACADEMIC_DIRECTOR, ROLE_TEACHER, ROLE_FINANCIAL
}
